### ISSUE TITLE
readme Typo

### ISSUE THREAD

**Issue by diaphel** [furious-luke/django-address#108]
In the readme you say to add the address app in the installed apps list, but you show an example of adding djang-filters as opposed to address

**Comment by banagale** [comment]
Oops. I was looking to have the readme reflect a more common syntax for the `INSTALLED_APPS` bit and did not edit my copy-pasta.  Fixed in  and added another better practice of commenting out the ellipsis that surround the package name.

Fixed in: af235abea94a839aa90ebdf8dc0382d9165629fb 

Thank you for pointing this out.
