### ISSUE TITLE
How to add extra address line for Apt/Unit#?

### ISSUE THREAD

**Issue by xjlin0** [furious-luke/django-address#141]
Great package!  Would it be possible to add one extra field of Address to enter extra info such as **apartment/floor/unit info** of the same street address?  Or should we add extra info in the route field instead? Here is my PR, please let me know if it's ok to add one such field, thanks!
https://github.com/furious-luke/django-address/pull/142
```
class Address(models.Model):
    extra = models.CharField(max_length=20, blank=True)
``` 
Also , since ordering will be `('locality', 'route', 'street_number', 'extra')`, probably it's better to add index to route/street_number/extra for the db performance.

**Comment by banagale** [comment]
Hello Jack, thank you for the praise and the PR.

I understand there could be use cases where having an apartment number/floor/unit specific field on the Address model would be useful.

However, I am reluctant to merge an arbitrary new extra field into the model at this stage to handle this.

The reason is the project is installed in many places and [there is already a goal](https://github.com/furious-luke/django-address/issues/98#issuecomment-676647511) to handle a better, more abstract model architecture.

I will look again at this as I look at other more basic improvements but probably would not accept this field.

Instead, I would suggest you use the Django Address model, but subclass it and add your `extra` field. This will allow you to continue to take updates as they may come in.

I did see your search error fix for admin. I haven't validated this but I can merge [that commit](https://github.com/furious-luke/django-address/commit/5be498b4117c530344433c72bc8010e8f073a918) once I do.

**Comment by xjlin0** [comment]
Sure no problems! thanks again for the suggestion, Merry Christmas and Happy New Year!

**Comment by banagale** [comment]
> Sure no problems! thanks again for the suggestion, Merry Christmas and Happy New Year!

You too.
