### ISSUE TITLE
Setting attrs for AddressWidget in django admin doesn't work

### ISSUE THREAD

**Issue by Marijus** [furious-luke/django-address#17]
from django.contrib import admin
from address.forms import AddressField, AddressWidget
from .models import Property

class PropertyAdmin(admin.ModelAdmin):
    formfield_overrides = {
        AddressField: {'widget': AddressWidget(attrs={"size": "150"})}
    }

setting the size to 150 doesn't work.

**Comment by furious-luke** [comment]
Hi Marijus,

I've written a new test to confirm that attributes passed to the widget are kept and rendered correctly, and they are indeed being rendered. Please see the test in `address/tests/forms.py` if you'd like to check.

I wonder if perhaps when you say it doesn't work you are actually saying that your widget is still the same size after specifying `size=150`, as opposed to the attributes are not being rendered? If that's the case, then the answer is because you're not specifying CSS sizes correctly. If you want to set the width of the widget via CSS directly on the widget class you will need to supply something like:
```
AddressWidget(attrs={"style": "width: 150px"})
```
Please note that while it's acceptable in Django to specify styles directly on the widget, I would not really recommend doing it this way; personally I prefer to restrict my styling to the templates to maintain a strict separation of form/view logic and presentation. But, each to their own!

Hope that helps! And please let me know if this has resolved your issue by replying to this comment so I can close the issue.

Cheers,
Luke

**Comment by Marijus** [comment]
Hey,

I've updated my code as you said but it seems to have no effect. Style attribute is not being rendered.

```<input class="address" id="id_address" name="address" type="text" placeholder="Enter a location" autocomplete="off">```

Here's what's being rendered.

**Comment by furious-luke** [comment]
Hi again Marijus,

Ah, I see your problem. The `formfield_overrides` requires keys that are model fields, not form fields. You're passing in the form field version of `AddressField`, instead of the one associated with the model. Please use `address.models.AddressField` instead, that should fix the issue.

Cheers,
Luke

**Comment by Marijus** [comment]
Hey Luke,

Changed it but it didn't help. Here's updated code:

from django.contrib import admin
from .models import Property

from address.models import AddressField
from address.forms import AddressWidget


class PropertyAdmin(admin.ModelAdmin):
    formfield_overrides = {
        AddressField: {'widget': AddressWidget(attrs={"style": "width: 150px"})}
    }

admin.site.register(Property, PropertyAdmin)

However I tried creating modelform and it worked:

from address.forms import AddressField, AddressWidget
from django import forms

class AddressForm(forms.Form):
  address = AddressField(widget=AddressWidget(attrs={"style": "width: 300px"}))

This works as it should.

**Comment by furious-luke** [comment]
I think perhaps there may be something else wrong with your code then, as the example site I've included in django-address shows that the wider width admin widget works as expected. Can you please take a look at the example site and check that the widget in the admin is wider?
