### ISSUE TITLE
Cut a 0.1.5 release?

### ISSUE THREAD

**Issue by jonblum** [furious-luke/django-address#39]
To bring #23 (HTTPS fixes) and #28 (Django 1.9 support) to PyPI

**Comment by furious-luke** [comment]
Sure thing, done.

Sorry for the delay in getting it up on PyPI. I've been working on the `dev` branch, which is aimed at solving the issue of handling addresses globally. I suspect I'll need to split the repository, as it's becoming vastly different to the `master` branch.

**Comment by jonblum** [comment]
Thanks!

**Comment by jgeerds** [comment]
I see no reason to split the repository. It should be enough to work on different branches (like now) and support the old version for a certain period of time (with semantic versioning)

**Comment by furious-luke** [comment]
The problem is that the interface to the data stored by the app is radically different in dev. If I was to move the dev branch to master then suddenly everyone's code would break, and require major overhauls. Because the API is so different it would be a substantial pain to try to support both the master interface and the dev one. It seems to me a solution that allows everyone currently using the master branch to keep using it without failure is to split the repo.

**Comment by furious-luke** [comment]
P.S. Thanks for your input, I've opened a ticket specifically addressing this concern to try and get some more input as to what users of `django-address` would prefer.
