### ISSUE TITLE
Unique constraint throws a warning.

### ISSUE THREAD

**Issue by macmichael01** [furious-luke/django-address#49]
Unique constraint throws a warning to use a OneToOneField instead of a ForeignKey.

**Comment by furious-luke** [comment]
Hi there, just wondering if you might be able to explain a little more about your issue? Ideally, if you could provide an example of how to replicate the issue that would be great.

**Comment by macmichael01** [comment]
`address = AddressField(unique=True)`

**Comment by furious-luke** [comment]
Ah okay, I understand your issue now. Yeah, `AddressField` is a subclassed `ForeignKey`, so this makes sense. I'll see if I can squash the warning, but in any case the unique constraint should still be enforced.

**Comment by banagale** [comment]
Thank you @macmichael01 for the report.

Since this warning has been addressed, I'm closing this ticket.

For future reference, I did make a note of the structural question of a FK rather than a onetoone [here](https://github.com/furious-luke/django-address/wiki/django-address-Model-Notes#uses-foreignkey-to-address).
